import AppKit
import SwiftUI

/// About tab for the Settings scene: app icon, name, version, tagline,
/// copyright. Fulfills VAL-UI-008 (Settings tabs) and VAL-PKG-003 (icon
/// visible in About).
///
/// The icon is pulled from `NSApp.applicationIconImage` so it reflects
/// whatever the bundle actually ships with — same image macOS uses in
/// the Dock and Finder. When running under SwiftUI previews or a
/// headless test host there may be no `NSApp`, so we fall back to a
/// loaded `NSImage(named: "AppIcon")`, then to an SF Symbol. This keeps
/// the view renderable in every context without reaching into the
/// bundle for the raw PNGs directly.
struct SettingsAboutTab: View {
    var body: some View {
        VStack(spacing: 16) {
            iconView
                .frame(width: 128, height: 128)
                .accessibilityHidden(true)

            Text("Kite")
                .font(.title).fontWeight(.semibold)

            Text(versionLine)
                .font(.system(size: 12))
                .foregroundStyle(.secondary)

            Text("A lightweight macOS git client.")
                .font(.system(size: 12))
                .multilineTextAlignment(.center)
                .foregroundStyle(.secondary)
                .padding(.horizontal, 32)

            Text(copyrightLine)
                .font(.system(size: 11))
                .foregroundStyle(.secondary)

            Spacer(minLength: 0)
        }
        .padding(32)
        .frame(maxWidth: .infinity, maxHeight: .infinity)
        .accessibilityIdentifier("Settings.About")
    }

    /// Icon pulled live from `NSApp` so the view reflects the built
    /// bundle's icon (regenerated by `scripts/generate_icon.swift`).
    /// Resolution order mirrors what the user would expect:
    ///   1. `NSApp.applicationIconImage` — in a running macOS app.
    ///   2. `NSImage(named: "AppIcon")` — previews / some test hosts.
    ///   3. SF Symbol placeholder — tests with no bundle image.
    @ViewBuilder
    private var iconView: some View {
        if let icon = NSApp?.applicationIconImage {
            Image(nsImage: icon)
                .resizable()
                .interpolation(.high)
                .scaledToFit()
        } else if let named = NSImage(named: "AppIcon") {
            Image(nsImage: named)
                .resizable()
                .interpolation(.high)
                .scaledToFit()
        } else {
            Image(systemName: "paperplane.fill")
                .resizable()
                .scaledToFit()
                .foregroundStyle(.tint)
        }
    }

    /// "Version X.Y.Z (build)" pulled from the host bundle's Info.plist.
    /// Falls back to "dev" / "0" so the view still renders under
    /// SwiftUI previews where bundle info is absent.
    private var versionLine: String {
        let info = Bundle.main.infoDictionary
        let marketing = info?["CFBundleShortVersionString"] as? String ?? "dev"
        let build = info?["CFBundleVersion"] as? String ?? "0"
        return "Version \(marketing) (\(build))"
    }

    /// Prefer the Info.plist value so the About panel and Finder's Get
    /// Info dialog never drift. Falls back to the same literal shipped
    /// in Info.plist if the key is missing (e.g. previews).
    private var copyrightLine: String {
        let info = Bundle.main.infoDictionary
        return info?["NSHumanReadableCopyright"] as? String ?? "© 2026 Ruben Langeweg"
    }
}
